#!/bin/sh

#EXTRA#
#DEBHELPER#

set -e

fixperms() {
    chown -R www-data:adm \
        /var/lib/roundcubemail \
        /var/log/roundcubemail
    chmod 750 \
        /var/lib/roundcubemail \
        /var/log/roundcubemail
	chown -R root:www-data /etc/roundcubemail
	find /etc/roundcubemail -type d -exec chmod u+rwx,g+rx,g-w,o-rwx {} \;
	find /etc/roundcubemail -type f -exec chmod u+rw,u-x,g+r,g-wx,o-rwx {} \;
}

reload_apache()
{
    if apache2ctl configtest 2>/dev/null; then
        invoke-rc.d apache2 $1 || true
    else
        echo "Your apache2 configuration is broken, so we're not restarting it for you."
    fi
}


case "$1" in
    configure)
        fixperms
        if [ -e "/etc/apache2/sites-available/roundcubemail" -a ! -e "/etc/apache2/sites-enabled/roundcubemail" ]; then
            a2ensite roundcubemail
            reload_apache reload
        fi
    ;;
esac

exit 0
